// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaUZo-1h2pnPskDSP8aj04vEjWOBYaFKQ',
    appId: '1:60027391828:web:9e1aaa7da16d987dae82c1',
    messagingSenderId: '60027391828',
    projectId: 'ecommerceapp-learning',
    authDomain: 'ecommerceapp-learning.firebaseapp.com',
    storageBucket: 'ecommerceapp-learning.firebasestorage.app',
    measurementId: 'G-BYJ8WYR7EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr0ZwezX8XTHPGTiULGmAcqP4T7s0WHI0',
    appId: '1:60027391828:android:14a7555b2f3e8e81ae82c1',
    messagingSenderId: '60027391828',
    projectId: 'ecommerceapp-learning',
    storageBucket: 'ecommerceapp-learning.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEvI1nYF4jFurDN0KPUqtl5QzmZPamhks',
    appId: '1:60027391828:ios:9cefc107ab59492bae82c1',
    messagingSenderId: '60027391828',
    projectId: 'ecommerceapp-learning',
    storageBucket: 'ecommerceapp-learning.firebasestorage.app',
    androidClientId: '60027391828-gp1640s9giirvcskq19qi4tdku5lnopo.apps.googleusercontent.com',
    iosClientId: '60027391828-2de2j4hqjba1aekthqj7n0vhd651i9rf.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceAdminPanel',
  );
}
